apiVersion: apps/v1
kind: Deployment
metadata:
  name: petstore
  namespace: petstore-feature
  labels:
    run: petstore
spec:
  replicas: 1
  selector:
    matchLabels:
      run: petstore
  template:
    metadata:
      labels:
        run: petstore
    spec:
      containers:
      - name: petstore
        image: petstore_feature:35
        ports:
        - containerPort: 80
          protocol: TCP
        env:
          - name: DBNAME
            value: petstore_feature
          - name: DBHOST
            value: petstore-mysql.default.svc.cluster.local
          - name: DBUSERNAME
            valueFrom:
              secretKeyRef: 
                name: dbcredentials
                key: dbusername
          - name: DBPASSWORD
            valueFrom:
              secretKeyRef: 
                name: dbcredentials
                key: dbpassword

