apiVersion: v1
kind: Namespace
metadata:
  name: petstore-feature

---

apiVersion: v1
kind: Secret
metadata:
  name: dbcredentials
  namespace: petstore-feature
type: Opaque
data:
  dbusername: cm9vdA==
  dbpassword: cm9vdA==

---

apiVersion: v1
kind: Service
metadata:
  name: petstore
  namespace: petstore-feature
  labels:
    run: petstore
spec:
  ports:
    - port: 82
      protocol: TCP
      targetPort: 80
  selector:
    run: petstore
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: petstore
  namespace: petstore-feature
  labels:
    run: petstore
spec:
  replicas: 4
  selector:
    matchLabels:
      run: petstore
  template:
    metadata:
      labels:
        run: petstore
    spec:
      containers:
      - name: petstore
        image: petstore_feature:38
        ports:
        - containerPort: 80
          protocol: TCP
        env:
          - name: DBNAME
            value: petstore_feature
          - name: DBHOST
            value: petstore-mysql.default.svc.cluster.local
          - name: DBUSERNAME
            valueFrom:
              secretKeyRef: 
                name: dbcredentials
                key: dbusername
          - name: DBPASSWORD
            valueFrom:
              secretKeyRef: 
                name: dbcredentials
                key: dbpassword
