apiVersion: v1
kind: Service
metadata:
  name: petstore
  namespace: petstore-feature
  labels:
    run: petstore
spec:
  ports:
    - port: 82
      protocol: TCP
      targetPort: 80
  selector:
    run: petstore
  type: LoadBalancer
