apiVersion: v1
kind: Service
metadata:
  name: rest-test
  namespace: default
  labels:
    run: rest-test
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    run: rest-test
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-test
  namespace: default
  labels:
    run: rest-test
spec:
  replicas: 4
  selector:
    matchLabels:
      run: rest-test
  template:
    metadata:
      labels:
        run: rest-test
    spec:
      containers:
      - name: rest-test
        env:
        - name: DBNAME
          valueFrom:
            secretKeyRef: 
              name: petdbinfo
              key: dbname
        image: petstore:24
        ports:
        - containerPort: 80
          protocol: TCP