apiVersion: v1
kind: Service
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{SERVICE_NAME}}-{{BRANCH_NAME}}
  labels:
    run: {{SERVICE_NAME}}
spec:
  ports:
    - port: {{EXTERNAL_PORT}}
      protocol: TCP
      targetPort: 80
  selector:
    run: {{SERVICE_NAME}}
  type: LoadBalancer
